[package]
name = "wh2ws"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.5"
log = "0.4.22"
rocket = "0.5.1"
rocket_ws = "0.1.1"
tokio = { version = "1.38.0", features = ["full"] }
